-- Launch contract. Apply manually through the approved Supabase/PostgreSQL migration path.
-- This migration is self-contained, additive, idempotent, and never drops existing data.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 1. BASE APPLICATION TABLES & COLUMNS (Additive & Idempotent)
-- ============================================================

-- 1.1 USERS (PK: UUID)
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  full_name TEXT,
  password TEXT,
  avatar TEXT,
  role TEXT NOT NULL DEFAULT 'client' CHECK (role IN ('super_admin', 'admin', 'manager', 'editor', 'client', 'visitor')),
  auth_provider TEXT DEFAULT 'email',
  discount_rate NUMERIC(3,2) DEFAULT 1.00,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'client';
ALTER TABLE users ADD COLUMN IF NOT EXISTS workspace_id UUID;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS persona_id UUID;
UPDATE users SET full_name = name WHERE full_name IS NULL AND name IS NOT NULL;

-- 1.2 WORKSPACES (PK: UUID)
CREATE TABLE IF NOT EXISTS workspaces (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  logo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.3 WORKSPACE MEMBERS (PK: composite workspace_id UUID, user_id UUID)
CREATE TABLE IF NOT EXISTS workspace_members (
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'client' CHECK (role IN ('super_admin','admin','manager','editor','client')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id)
);

-- Supabase Auth identity synchronization
CREATE OR REPLACE FUNCTION public.handle_supabase_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_provider TEXT;
BEGIN
  -- Normalize auth_provider to 'google' or 'email' to comply with users_auth_provider_check
  IF COALESCE(NEW.raw_app_meta_data ->> 'provider', NEW.app_metadata ->> 'provider', '') = 'google' THEN
    v_provider := 'google';
  ELSE
    v_provider := 'email';
  END IF;

  INSERT INTO public.users (id, email, name, full_name, avatar, auth_provider, role, is_verified, is_active)
  SELECT NEW.id,
         NEW.email,
         COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.raw_user_meta_data ->> 'name', NEW.email),
         COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.raw_user_meta_data ->> 'name', NEW.email),
         COALESCE(NEW.raw_user_meta_data ->> 'avatar_url', NEW.raw_user_meta_data ->> 'picture'),
         v_provider,
         'client',
         NEW.email_confirmed_at IS NOT NULL,
         true
  WHERE NOT EXISTS (SELECT 1 FROM public.users WHERE id = NEW.id OR email = NEW.email);
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_supabase_auth_user();

-- 1.4 SERVICES (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  level TEXT NOT NULL DEFAULT '1',
  price NUMERIC(10,2) NOT NULL DEFAULT 0,
  duration_days INTEGER,
  is_active BOOLEAN DEFAULT true,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE services ADD COLUMN IF NOT EXISTS persona_ids JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE services ADD COLUMN IF NOT EXISTS requirements TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS prompt TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS name_en TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS name_tr TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS description_en TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS description_tr TEXT;

-- 1.5 PACKAGES (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  features JSONB DEFAULT '[]'::jsonb,
  is_popular BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE packages ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS services JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS persona_ids JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- 1.6 PROJECTS (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  created_by UUID REFERENCES users(id),
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.7 ORDERS (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id TEXT DEFAULT (gen_random_uuid())::text,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  package TEXT,
  service TEXT,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'processing', 'completed', 'cancelled', 'refunded')),
  txid TEXT,
  file_url TEXT,
  file_path TEXT,
  attachments JSONB,
  price NUMERIC(10,2),
  amount NUMERIC(10,2),
  network TEXT DEFAULT 'polygon',
  currency TEXT DEFAULT 'USDC',
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  workspace_id UUID REFERENCES workspaces(id),
  project_id BIGINT REFERENCES projects(id) ON DELETE SET NULL,
  package_id BIGINT REFERENCES packages(id),
  payment_status TEXT NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending','submitted','verified','failed','refunded')),
  delivered_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS workspace_id UUID REFERENCES workspaces(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS submission_id TEXT DEFAULT (gen_random_uuid())::text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending','submitted','verified','failed','refunded'));
ALTER TABLE orders ADD COLUMN IF NOT EXISTS txid TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS project_id BIGINT REFERENCES projects(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX IF NOT EXISTS orders_submission_id_key ON orders(submission_id);
CREATE INDEX IF NOT EXISTS orders_workspace_id_idx ON orders(workspace_id);
CREATE INDEX IF NOT EXISTS orders_project_id_idx ON orders(project_id);

-- 1.8 PAYMENTS (PK: UUID, FK: order_id BIGINT REFERENCES orders(id))
CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  transaction_id TEXT UNIQUE,
  network TEXT NOT NULL DEFAULT 'polygon',
  currency TEXT NOT NULL DEFAULT 'USDC',
  expected_amount NUMERIC(12,2) NOT NULL CHECK (expected_amount > 0),
  submitted_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','submitted','verified','failed','refunded')),
  verification_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.9 ORDER EVENTS (PK: UUID, FK: order_id BIGINT REFERENCES orders(id))
CREATE TABLE IF NOT EXISTS order_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES users(id),
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.10 ORDER FILES (PK: UUID, FK: order_id BIGINT REFERENCES orders(id))
CREATE TABLE IF NOT EXISTS order_files (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  uploaded_by UUID NOT NULL REFERENCES users(id),
  object_path TEXT NOT NULL UNIQUE,
  original_name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  byte_size BIGINT NOT NULL CHECK (byte_size >= 0),
  file_kind TEXT NOT NULL CHECK (file_kind IN ('customer_input','delivery','internal')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.11 INVOICES (PK: BIGINT, FK: order_id BIGINT REFERENCES orders(id))
CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
  invoice_number TEXT NOT NULL UNIQUE,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  tax NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (tax >= 0),
  total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
  status TEXT NOT NULL DEFAULT 'issued' CHECK (status IN ('issued','paid','void','refunded')),
  pdf_url TEXT,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.12 TICKETS (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_id UUID REFERENCES workspaces(id),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','resolved','closed')),
  admin_response TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE tickets ADD COLUMN IF NOT EXISTS workspace_id UUID REFERENCES workspaces(id);

-- 1.13 CONVERSATIONS (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  workspace_id UUID REFERENCES workspaces(id),
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  title TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE conversations ADD COLUMN IF NOT EXISTS workspace_id UUID REFERENCES workspaces(id);
CREATE UNIQUE INDEX IF NOT EXISTS conversations_order_id_idx ON conversations(order_id) WHERE order_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS conversations_project_id_idx ON conversations(project_id) WHERE project_id IS NOT NULL;

-- 1.14 MESSAGES (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES users(id),
  content TEXT NOT NULL CHECK (char_length(content) BETWEEN 1 AND 5000),
  read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.15 NOTIFICATIONS (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'status_update',
  read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.16 SUBSCRIPTIONS (PK: UUID in live DB)
CREATE TABLE IF NOT EXISTS subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  plan_type TEXT DEFAULT 'life_plan',
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'cancelled', 'expired')),
  payment_method TEXT DEFAULT 'USDC',
  payment_tx_hash TEXT,
  price NUMERIC(10,2) DEFAULT 49.00,
  start_date TIMESTAMPTZ DEFAULT now(),
  end_date TIMESTAMPTZ,
  auto_renew BOOLEAN DEFAULT true,
  started_at TIMESTAMPTZ DEFAULT now(),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 1.17 DIGITAL PRODUCTS (PK: UUID in live DB)
CREATE TABLE IF NOT EXISTS digital_products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  file_url TEXT,
  preview_url TEXT,
  thumbnail TEXT,
  category TEXT NOT NULL,
  downloads_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 1.18 DONATIONS (PK: UUID)
CREATE TABLE IF NOT EXISTS donations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  donor_name TEXT,
  donor_email TEXT,
  amount NUMERIC(10,2) NOT NULL,
  currency TEXT DEFAULT 'USDC',
  cause TEXT DEFAULT 'Gaza Emergency Relief',
  txid TEXT,
  message TEXT,
  is_anonymous BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 1.19 BLOG POSTS (PK: UUID in live DB)
CREATE TABLE IF NOT EXISTS blog_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title JSONB NOT NULL,
  excerpt JSONB,
  content JSONB,
  category TEXT,
  cover_image TEXT,
  published_at TIMESTAMPTZ,
  read_time INTEGER DEFAULT 5,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 1.20 PORTFOLIO (PK: UUID in live DB)
CREATE TABLE IF NOT EXISTS portfolio (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title JSONB NOT NULL,
  description JSONB,
  category TEXT,
  image_url TEXT,
  link TEXT,
  technologies TEXT[],
  completed_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 1.21 FAQS (PK: UUID in live DB)
CREATE TABLE IF NOT EXISTS faqs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question JSONB NOT NULL,
  answer JSONB NOT NULL,
  category TEXT,
  order_index INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 1.22 PERSONAS (PK: UUID)
CREATE TABLE IF NOT EXISTS personas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  name_ar TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1.23 TRANSLATIONS (PK: BIGINT in live DB)
CREATE TABLE IF NOT EXISTS translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lang TEXT NOT NULL,
  ns TEXT NOT NULL DEFAULT 'common',
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS workspace_members_user_idx ON workspace_members(user_id);
CREATE INDEX IF NOT EXISTS payments_order_idx ON payments(order_id);
CREATE INDEX IF NOT EXISTS order_events_order_idx ON order_events(order_id, created_at);
CREATE INDEX IF NOT EXISTS order_files_order_idx ON order_files(order_id);
CREATE INDEX IF NOT EXISTS messages_conversation_idx ON messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS notifications_user_idx ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS tickets_workspace_id_idx ON tickets(workspace_id);
CREATE INDEX IF NOT EXISTS conversations_workspace_id_idx ON conversations(workspace_id);

-- ============================================================
-- 2. ATOMIC PAYMENT VERIFICATION FUNCTION
-- ============================================================
CREATE OR REPLACE FUNCTION verify_payment_and_order(
  p_payment_id UUID,
  p_transaction_id TEXT,
  p_network TEXT,
  p_currency TEXT,
  p_amount_units NUMERIC,
  p_confirmations INTEGER,
  p_block_number TEXT,
  p_token_address TEXT,
  p_recipient_address TEXT
) RETURNS payments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_payment payments;
  v_order orders;
BEGIN
  SELECT * INTO v_payment FROM payments WHERE id = p_payment_id FOR UPDATE;
  IF NOT FOUND OR v_payment.status <> 'submitted' OR v_payment.transaction_id <> p_transaction_id THEN
    RAISE EXCEPTION 'payment is not awaiting verification';
  END IF;
  SELECT * INTO v_order FROM orders WHERE id = v_payment.order_id FOR UPDATE;
  IF NOT FOUND OR v_order.payment_status <> 'submitted' THEN
    RAISE EXCEPTION 'order is not awaiting payment verification';
  END IF;
  IF EXISTS (SELECT 1 FROM payments WHERE transaction_id = p_transaction_id AND id <> p_payment_id) THEN
    RAISE EXCEPTION 'transaction has already been used';
  END IF;
  UPDATE payments SET status = 'verified', verified_at = now(), updated_at = now(),
    network = p_network, currency = p_currency,
    verification_reason = jsonb_build_object('amount_units', p_amount_units, 'confirmations', p_confirmations, 'block_number', p_block_number, 'token_address', lower(p_token_address), 'recipient_address', lower(p_recipient_address))::text
    WHERE id = p_payment_id RETURNING * INTO v_payment;
  UPDATE orders SET payment_status = 'verified', txid = p_transaction_id, updated_at = now()
    WHERE id = v_order.id AND payment_status = 'submitted';
  IF NOT FOUND THEN RAISE EXCEPTION 'order verification race'; END IF;
  RETURN v_payment;
END;
$$;
REVOKE EXECUTE ON FUNCTION verify_payment_and_order(UUID, TEXT, TEXT, TEXT, NUMERIC, INTEGER, TEXT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION verify_payment_and_order(UUID, TEXT, TEXT, TEXT, NUMERIC, INTEGER, TEXT, TEXT, TEXT) TO service_role;

-- ============================================================
-- 3. ROW LEVEL SECURITY & ACCESS POLICIES
-- ============================================================
ALTER TABLE workspace_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "members view own memberships" ON workspace_members;
CREATE POLICY "members view own memberships" ON workspace_members FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "members view own workspaces" ON workspaces;
CREATE POLICY "members view own workspaces" ON workspaces FOR SELECT USING (
  EXISTS (SELECT 1 FROM workspace_members WHERE workspace_members.workspace_id = workspaces.id AND workspace_members.user_id = auth.uid())
);

DROP POLICY IF EXISTS "customers view own orders" ON orders;
CREATE POLICY "customers view own orders" ON orders FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "customers view own payments" ON payments;
CREATE POLICY "customers view own payments" ON payments FOR SELECT USING (EXISTS (SELECT 1 FROM orders WHERE orders.id = payments.order_id AND orders.user_id = auth.uid()));

DROP POLICY IF EXISTS "customers view own order events" ON order_events;
CREATE POLICY "customers view own order events" ON order_events FOR SELECT USING (EXISTS (SELECT 1 FROM orders WHERE orders.id = order_events.order_id AND orders.user_id = auth.uid()));

DROP POLICY IF EXISTS "customers view own files" ON order_files;
CREATE POLICY "customers view own files" ON order_files FOR SELECT USING (EXISTS (SELECT 1 FROM orders WHERE orders.id = order_files.order_id AND orders.user_id = auth.uid()));

DROP POLICY IF EXISTS "members view workspace projects" ON projects;
CREATE POLICY "members view workspace projects" ON projects FOR SELECT USING (
  EXISTS (SELECT 1 FROM workspace_members WHERE workspace_members.workspace_id = projects.workspace_id AND workspace_members.user_id = auth.uid())
);

DROP POLICY IF EXISTS "customers view own invoices" ON invoices;
CREATE POLICY "customers view own invoices" ON invoices FOR SELECT USING (EXISTS (SELECT 1 FROM orders WHERE orders.id = invoices.order_id AND orders.user_id = auth.uid()));

DROP POLICY IF EXISTS "customers manage own tickets" ON tickets;
CREATE POLICY "customers manage own tickets" ON tickets FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "customers view own conversations" ON conversations;
CREATE POLICY "customers view own conversations" ON conversations FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "customers view own messages" ON messages;
CREATE POLICY "customers view own messages" ON messages FOR SELECT USING (EXISTS (SELECT 1 FROM conversations WHERE conversations.id = messages.conversation_id AND conversations.user_id = auth.uid()));

DROP POLICY IF EXISTS "customers view own notifications" ON notifications;
CREATE POLICY "customers view own notifications" ON notifications FOR SELECT USING (auth.uid() = user_id);
