-- BİSHIŞ V1 — Execution Engine Foundation
-- Additive and idempotent. No destructive data operation.

CREATE TABLE IF NOT EXISTS project_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS project_template_milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL REFERENCES project_templates(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  position INTEGER NOT NULL CHECK (position >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (template_id, position)
);
CREATE TABLE IF NOT EXISTS project_template_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_milestone_id BIGINT NOT NULL REFERENCES project_template_milestones(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high','urgent')),
  position INTEGER NOT NULL CHECK (position >= 0),
  client_visible BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (template_milestone_id, position)
);
CREATE TABLE IF NOT EXISTS project_milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  position INTEGER NOT NULL CHECK (position >= 0),
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started','in_progress','completed','blocked')),
  start_date DATE,
  due_date DATE,
  completed_at TIMESTAMPTZ,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (project_id, position)
);
CREATE TABLE IF NOT EXISTS project_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  milestone_id BIGINT REFERENCES project_milestones(id) ON DELETE SET NULL,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo','in_progress','blocked','done','cancelled')),
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high','urgent')),
  assignee_id UUID REFERENCES users(id) ON DELETE SET NULL,
  due_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  client_visible BOOLEAN NOT NULL DEFAULT false,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS project_activity (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES users(id) ON DELETE SET NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('project','milestone','task','order','file','message','ticket')),
  entity_id TEXT,
  event_type TEXT NOT NULL,
  visibility TEXT NOT NULL DEFAULT 'internal' CHECK (visibility IN ('internal','client')),
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS project_templates_service_idx ON project_templates(service_id);
CREATE INDEX IF NOT EXISTS template_milestones_template_idx ON project_template_milestones(template_id, position);
CREATE INDEX IF NOT EXISTS template_tasks_milestone_idx ON project_template_tasks(template_milestone_id, position);
CREATE INDEX IF NOT EXISTS project_milestones_project_idx ON project_milestones(project_id, position);
CREATE INDEX IF NOT EXISTS project_tasks_project_status_idx ON project_tasks(project_id, status, priority);
CREATE INDEX IF NOT EXISTS project_tasks_milestone_idx ON project_tasks(milestone_id);
CREATE INDEX IF NOT EXISTS project_tasks_due_idx ON project_tasks(due_at) WHERE status NOT IN ('done','cancelled');
CREATE INDEX IF NOT EXISTS project_activity_project_created_idx ON project_activity(project_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.execution_role() RETURNS TEXT LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT role FROM public.users WHERE id = auth.uid() AND is_active = true LIMIT 1;
$$;
CREATE OR REPLACE FUNCTION public.execution_is_staff() RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.execution_role() IN ('admin','super_admin','manager','editor');
$$;
CREATE OR REPLACE FUNCTION public.execution_can_access_project(p_project_id BIGINT) RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.execution_role() = 'super_admin' OR EXISTS (
    SELECT 1 FROM public.projects p JOIN public.workspace_members wm ON wm.workspace_id = p.workspace_id
    WHERE p.id = p_project_id AND wm.user_id = auth.uid()
  );
$$;
REVOKE ALL ON FUNCTION public.execution_role() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.execution_is_staff() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.execution_can_access_project(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.execution_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.execution_is_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.execution_can_access_project(BIGINT) TO authenticated;

ALTER TABLE project_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_template_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_template_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_activity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "execution staff templates" ON project_templates;
CREATE POLICY "execution staff templates" ON project_templates FOR ALL USING (public.execution_is_staff()) WITH CHECK (public.execution_is_staff());
DROP POLICY IF EXISTS "execution staff template milestones" ON project_template_milestones;
CREATE POLICY "execution staff template milestones" ON project_template_milestones FOR ALL USING (public.execution_is_staff()) WITH CHECK (public.execution_is_staff());
DROP POLICY IF EXISTS "execution staff template tasks" ON project_template_tasks;
CREATE POLICY "execution staff template tasks" ON project_template_tasks FOR ALL USING (public.execution_is_staff()) WITH CHECK (public.execution_is_staff());
DROP POLICY IF EXISTS "execution view milestones" ON project_milestones;
CREATE POLICY "execution view milestones" ON project_milestones FOR SELECT USING (
  public.execution_can_access_project(project_id) AND (public.execution_is_staff() OR (public.execution_role() = 'client' AND EXISTS (SELECT 1 FROM project_tasks t WHERE t.milestone_id = project_milestones.id AND t.client_visible)))
);
DROP POLICY IF EXISTS "execution manage milestones" ON project_milestones;
CREATE POLICY "execution manage milestones" ON project_milestones FOR ALL USING (public.execution_is_staff() AND public.execution_can_access_project(project_id)) WITH CHECK (public.execution_is_staff() AND public.execution_can_access_project(project_id));
DROP POLICY IF EXISTS "execution view tasks" ON project_tasks;
CREATE POLICY "execution view tasks" ON project_tasks FOR SELECT USING (public.execution_can_access_project(project_id) AND (public.execution_is_staff() OR (public.execution_role() = 'client' AND client_visible)));
DROP POLICY IF EXISTS "execution manage tasks" ON project_tasks;
CREATE POLICY "execution manage tasks" ON project_tasks FOR ALL USING (public.execution_is_staff() AND public.execution_can_access_project(project_id)) WITH CHECK (public.execution_is_staff() AND public.execution_can_access_project(project_id));
DROP POLICY IF EXISTS "execution view activity" ON project_activity;
CREATE POLICY "execution view activity" ON project_activity FOR SELECT USING (public.execution_can_access_project(project_id) AND (public.execution_is_staff() OR (public.execution_role() = 'client' AND visibility = 'client')));
DROP POLICY IF EXISTS "execution insert activity" ON project_activity;
CREATE POLICY "execution insert activity" ON project_activity FOR INSERT WITH CHECK (public.execution_is_staff() AND public.execution_can_access_project(project_id));

NOTIFY pgrst, 'reload schema';
