-- BİŞIŞ V1 — Service Delivery Engine additive contract
-- No destructive operations. Do not run database/legacy/schema.sql.

ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS execution_state TEXT NOT NULL DEFAULT 'not_started';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS waiting_on TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS state_updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projects_execution_state_check') THEN
    ALTER TABLE public.projects ADD CONSTRAINT projects_execution_state_check
      CHECK (execution_state IN ('not_started','waiting_on_client','waiting_on_founder','in_progress','blocked','ready_for_review','ready_for_delivery','waiting_on_review','completed'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projects_waiting_on_check') THEN
    ALTER TABLE public.projects ADD CONSTRAINT projects_waiting_on_check
      CHECK (waiting_on IS NULL OR waiting_on IN ('client','founder','payment','review'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS projects_execution_state_idx ON public.projects(execution_state, waiting_on);

CREATE TABLE IF NOT EXISTS public.project_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 180),
  description TEXT NOT NULL DEFAULT '',
  requirement_type TEXT NOT NULL DEFAULT 'text' CHECK (requirement_type IN ('text','file','choice')),
  is_required BOOLEAN NOT NULL DEFAULT true,
  status TEXT NOT NULL DEFAULT 'requested' CHECK (status IN ('requested','submitted','needs_revision','approved','not_applicable')),
  response_value TEXT,
  file_id UUID REFERENCES public.order_files(id) ON DELETE SET NULL,
  client_visible BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS project_requirements_project_idx ON public.project_requirements(project_id, status, is_required);
CREATE INDEX IF NOT EXISTS project_requirements_file_idx ON public.project_requirements(file_id) WHERE file_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.project_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL UNIQUE REFERENCES public.projects(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'ready_for_delivery' CHECK (status IN ('ready_for_delivery','prepared','delivered','client_review','approved','revision_requested','completed')),
  notes TEXT NOT NULL DEFAULT '',
  revision_reason TEXT,
  revision_count INTEGER NOT NULL DEFAULT 0 CHECK (revision_count BETWEEN 0 AND 5),
  prepared_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  prepared_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS project_deliveries_status_idx ON public.project_deliveries(status);

CREATE OR REPLACE FUNCTION public.execution_client_can_access_project(p_project_id BIGINT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.projects p
    JOIN public.orders o ON o.project_id = p.id
    WHERE p.id = p_project_id
      AND o.user_id = auth.uid()
  );
$$;

REVOKE ALL ON FUNCTION public.execution_client_can_access_project(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.execution_client_can_access_project(BIGINT) TO authenticated;

ALTER TABLE public.project_requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_deliveries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service delivery staff requirements" ON public.project_requirements;
CREATE POLICY "service delivery staff requirements" ON public.project_requirements
  FOR ALL
  USING (public.execution_is_staff() AND public.execution_can_access_project(project_id))
  WITH CHECK (public.execution_is_staff() AND public.execution_can_access_project(project_id));

DROP POLICY IF EXISTS "service delivery client requirements" ON public.project_requirements;
CREATE POLICY "service delivery client requirements" ON public.project_requirements
  FOR SELECT
  USING (public.execution_client_can_access_project(project_id) AND client_visible = true);

DROP POLICY IF EXISTS "service delivery staff deliveries" ON public.project_deliveries;
CREATE POLICY "service delivery staff deliveries" ON public.project_deliveries
  FOR ALL
  USING (public.execution_is_staff() AND public.execution_can_access_project(project_id))
  WITH CHECK (public.execution_is_staff() AND public.execution_can_access_project(project_id));

DROP POLICY IF EXISTS "service delivery client deliveries" ON public.project_deliveries;
CREATE POLICY "service delivery client deliveries" ON public.project_deliveries
  FOR SELECT
  USING (public.execution_client_can_access_project(project_id));

NOTIFY pgrst, 'reload schema';
